name: GoSelectCI-ubuntu-latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.17]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Run unit and integration test coverage
        run: go test -coverprofile=coverage.out -coverpkg=./... -covermode=atomic --tags=unit,integration -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run functional tests
        run: go test --tags=functional -v ./...

      - name: Build
        run: go build -v ./...
